version: '3.8'

services:
  db:
    image: postgres:15
    container_name: asset_db
    restart: always
    environment:
      POSTGRES_DB: assets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./assets-manager-backend
    container_name: asset_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/assets
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build: ./assets-manager-frontend
    container_name: asset_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
